== Objetos Digitais de Aprendizagem: Definição e Conceitos

:cap: cap1
:img: images/{cap}
:online: {gitrepo}/blob/master/livro/code/{cap}
:local: code/{cap}

.Objetivos do capítulo
____
Ao final deste capítulo você deverá ser capaz de:

1. Lembrar a importância dos objetos digitais de aprendizagem,
enumerando possíveis usos em sala de aula;

Lembrar Conhecimento da Terminologia
Objeto de Aprendizagem
Analógico
Digital

Entender Objeto de Aprendizagem Digital (ODA)


2. Entender a definição de um objeto digital de aprendizagem,
identificando-os em um universo de recursos;

3. Aplicar o conceito de objetos digitais de aprendizagem, citando
suas características; 

4. Analisar as características de um objeto digital de aprendizagem,
reconhecendo-as no objeto.

____


A tecnologia está cada vez mais presente em nosso dia-a-dia, tornando
nossas tarefas mais práticas e funcionais, seja no trabalho ou em
casa. Até mesmo o nosso lazer é influenciado pela facilidade de
comunicação e acesso à internet. Diante desse contexto, é esperado que
conteúdos tradicionais com as tecnologias disponíveis e obtendo assim
a escola também esteja inserida no meio digital, articulando os
uma aproximação do trio tecnologia-aluno-professor. 

Uma forma de utilização da tecnologia em sala de aula, tanto no ensino
presencial quanto no ensino a distância, tem se dado por meio dos
*objetos digitais de aprendizagem*. Esses recursos técnico-pedagógicos
vem ganhando cada vez mais espaço e importância ao fornecerem um
suporte efetivo ao processo de ensino-aprendizagem, atuando como um
facilitador e promovedor do desenvolvimento cognitivo. 

O objeto de aprendizagem é um recurso que pode auxiliar o professor em
diferentes contextos, podendo ser basicamente:

Aberto:: São aqueles que contem ferramentas para a criação de recursos
por parte dos alunos ou professor. Ex: softwares;

Instrucional:: São os do tipo tutoriais. Ex: livros da EAD;

Exploratório:: Nestes os alunos podem fazer experiências. Ex: jogos
educativos;

Auxiliar:: Ajudam na resolução de problemas. Ex: vídeos instrucionais;

Comunicacionais:: Potencializam a interação entre os indivíduos,
favorecendo a discussão e troca de ideias. Ex: blogs com material
didático;

Certamente você já usou alguns desses recursos para auxiliá-lo no seu
aprendizado. Só não sabiam, talvez, que esses recursos se chamavam
Objetos Digitais de Aprendizagem.


=== Atividade 1

Descreva um objetivo para o uso didático de cada um dos 3 objetos
digitais de aprendizagem citados na tabela abaixo

|====
| História em Quadrinhos |
| Questionário on-line |
| Audiobook |
|====


Solução: Uma história em quadrinhos pode ser usada com o objetivo de
introduzir conceitos a partir da conversa de dois personagens sobre um
conteúdo novo. Um questionário on-line pode ser usado com o objetivo
de avaliação. Os audiobooks tem por objetivo permitir o acesso ao
conteúdo didático por portadores de necessidades especiais. Obs: Essa
solução não é única!

A terminologia *((Objetos de Aprendizagem))* foi adotada pelo _Learning
Technology Standards Committee (LTSC)_ do _Institute of Electrical and
Electronics Engineers (IEEE)_, que os define em sua norma 1484 como uma
entidade, digital ou não digital, que pode ser usada para
aprendizagem, educação e treinamento.

Como podemos ver, essa definição é bastante ampla, e nesse caso seriam
objetos de aprendizagem os conteúdos multimídia, softwares
educacionais, pessoas, organizações, livros, etc. 

São muitas as definições de objetos de aprendizagem, dizem até que
existem tantas definições quanto seus usuários. Cada uma delas está
correta no seu ponto de vista e dentro das características que aponta.

O curso “Seminário Temático: Objetos Digitais de Educação em
Computação” pretende focar o estudo em objetos _digitais_. Nesse caso
adotaremos a definição de Wiley, que restringe a ampla definição de
Objetos de Aprendizagem a “qualquer recurso _digital_ que pode ser
reusado para apoiar atividades de ensino-aprendizagem”. Esse conceito
apresenta algumas vantagens, a principal delas é reduzir o universo em
que estes recursos se incluem, visto que estamos interessados apenas
naqueles digitais. 

=== Atividade 2

Marque com um x as figuras que representam objetos digitais de aprendizagem

[NOTE]
.Solução
====

São objetos digitais de aprendizagem a revista, o gráfico, as vídeo
aulas e os jogos. O professor e o lego são objetos de aprendizagem,
mas não são digitais.

====

Os objetos digitais de aprendizagem podem ser criados em qualquer
mídia ou formato, variando desde uma simples imagem até um complexo
software. De acordo com padrões internacionais que pautam aspectos dos
objetos de aprendizagem, é necessário que eles devam, como toda
atividade de ensino, apresentar propósito educacional bem definido,
ser instigantes e envolventes para estimular a reflexão do aluno e
possam ser aplicados diversas vezes e em várias situações. Para
satisfazer esse último quesito, o objeto de aprendizagem normalmente
trabalha com  pequena parte do conteúdo curricular, sendo bem
específico dentro de um assunto amplo (essa propriedade se chama
granularidade).  Assim, as principais características de um objeto de
aprendizagem se resumem a:

Reusabilidade:: deve ser reutilizável diversas vezes em diversas
situações e ambientes de aprendizagem, como por exemplo um objeto que
possa ser usado tanto no ensino presencial quanto no ensino a
distância e tanto no Brasil como no México;

Granularidade:: deve apresentar conteúdo bem específico, para
facilitar o seu uso e reuso, como por exemplo um objeto que auxilie no
aprendizado do conceito de frações;

Acessibilidade:: ser facilmente acessível para ser usado em diversos
locais ou, ainda, ser potencialmente acessível a usuários com
necessidades especiais; por exemplo um blog com conteúdo de
trigonometria ou um audiobook;

Durabilidade:: apresentar possibilidade de continuar a ser usado
independente de mudança de tecnologia. Isso significa que um objeto
que era usado em um equipamento mais antigo deve poder ser utilizado
em um equipamento moderno, tendo em vista a rapidez com que nossa
tecnologia se torna obsoleta;

Interoperabilidade:: apresentar possibilidade de operar através de
variedade de hardwares, sistemas operacionais e browsers. Isso
significa que um objeto deve funcionar em Linux, Windows e ser
acessado usando Firefox, Explorer ou Chromium por exemplo;


Veja que a granularidade determina a reusabilidade, dado que um objeto
de grande extensão dificulta a sua reutilização, adaptabilidade e
acessibilidade; sendo então uma característica fundamental para
maximizar a eficiência de um objeto de aprendizagem. Além disso, um
objeto com grande cobertura de conteúdo dispersa do objetivo principal
e sua utilização não deve durar mais do que alguns minutos para manter
o foco no objetivo.

As propriedades de interoperabilidade e reusabilidade são essenciais
para se garantir o amadurecimento e a popularização da utilização dos
objetos digitais na sala de aula. 

Devido a grande demanda de objetos digitais de aprendizagem
disponibilizados na internet e outros meios,  surgiu a necessidade de
se fazer uma padronização das tecnologias de aprendizagem. Com esses
elementos (grânulos) já padronizados, a busca, uso, reuso tornam-se
mais fáceis já que dessa forma eles podem ser armazenados em
repositórios de metadados.

Independente do tipo de padronização a ser seguido, o objeto de
aprendizagem pode ser dividido em três partes distintas:

O objetivo:: em que o aprendiz busca as informações a respeito do
campo em que o seu objeto de aprendizagem vai intervir; 

O conteúdo:: no qual serão previstas as ferramentas de criação de um
objeto de aprendizagem; 

A prática:: ou feedback, que é quando o aprendiz irá fazer os testes
necessários no objeto de aprendizagem para verificar se o objeto
supriu as expectativas propostas nos objetivos. 

=== Atividade 3

Liste no quadro abaixo 5 características dos objetos digitais de
aprendizagem e descreva, em poucas palavras, o que cada uma
representa.

|====
|
|
|
|
|
|====

.Solução
[NOTE]
====

Reusabilidade – usar em mais de uma situação, granularidade – objetos
de pequeno porte, acessibilidade – facilitar o acesso ao usuário,
durabilidade – não tornar-se rapidamente obsoleto, interoperabilidade –
funcionar na máquina que o usuário utiliza.

====


=== Atividade 4

Considere o seguinte objeto digital de aprendizagem: uma apresentação
feita em power point e convertida para pdf. Explique porque ele
satisfaz as 5 condições descritas na atividade 3.

[NOTE]
.Solução
====

A apresentação pode ser reutilizada para outro curso ou evento; trata
de um assunto específico e nunca de um curso inteiro; pode ser
disponibilizada na internet, cd, dvd e pendrive; pode ser acessada em
um computador obsoleto ou de última geração, incluindo equipamentos
portáteis; o arquivo abre em qualquer sistema operacional sem perda de
formatação.

====

Os recursos educacionais multimídia interativos, na forma de objetos
de aprendizagem, tem sido muito bem aceitos no meio educacional.
Inúmeros recursos didáticos para uso no computador são desenvolvidos e
disponibilizados para uso público todos os dias. Porém, deve haver
cuidado na hora da escolha do material a ser utilizado, devendo ter
atenção nos quesitos _qualidade_ e _pertinência_ do recurso digital
disponível. Na próxima seção veremos as características que descrevem
um bom objeto digital de aprendizagem sob uma perspectiva tanto
técnica quanto pedagógica. 
