=== O que são Objetos de Aprendizagem Digitais?

==== Objeto de Aprendizagem

(((Objeto de Aprendizagem)))

Todo.

==== Objeto Analógico

(((Analógico)))

Todo.

==== Objeto Digital

(((Digital)))

Todo.

==== Objeto de Aprendizagem Digital (OAD)

(((Objeto de Aprendizagem Digital)))

A terminologia *Objetos de Aprendizagem* foi adotada pelo _Learning
Technology Standards Committee (LTSC) do Institute of Electrical and
Electronics Engineers (IEEE)_, que os define em sua norma 1484 como
uma entidade, digital ou não digital, que pode ser usada para
aprendizagem, educação e treinamento.

Como podemos ver, essa definição é bastante ampla, e nesse caso seriam
objetos de aprendizagem os conteúdos multimídia, softwares
educacionais, pessoas, organizações, livros, etc. 

São muitas as definições de objetos de aprendizagem, dizem até que
existem tantas definições quanto seus usuários. Cada uma delas está
correta no seu ponto de vista e dentro das características que aponta.

O curso “Seminário Temático: Objetos Digitais de Educação em
Computação” pretende focar o estudo em objetos *digitais*. Nesse caso
adotaremos a definição de Wiley, que restringe a ampla definição de
Objetos de Aprendizagem a “qualquer recurso *digital* que pode ser
reusado para apoiar atividades de ensino-aprendizagem”. Esse conceito
apresenta algumas vantagens, a principal delas é reduzir o universo em
que estes recursos se incluem, visto que estamos interessados apenas
naqueles digitais. 

==== Atividade: reconhecendo recursos digitais e analógicos
Todo.

Resposta comentada: TODO.

[TIP]
.Feedback
====

TODO.

====


==== Atividade: classificando e explicando os objetos apresentados
Todo.
São OA
Caneta
Computador
Calculadora
Livro, Revista
Software de controle de vendas
Não são
Grampeador
Balança de pesar pessoas
Copo medidor
Copo comum

Resposta comentada:


[TIP]
.Feedback
====

Depende do contexto do uso (feedback)

====
