Se um médico do século passado viajasse no tempo e chegasse hoje para
trabalhar em um hospital, certamente seria incapaz de operar os
equipamentos ou mesmo avaliar exames de seus pacientes, dados os
avanços tecnológicos que ocorreram desde então. Da mesma forma, um
contador que trabalha atualmente não usa mais os clássicos cadernos
diário-razão-caixa de antigamente, seu material agora é informatizado.
Mas o que aconteceria se um professor do século passado chegasse hoje
em uma sala de aula?

A resposta é simples: *ele daria aula*!

Isso deveria nos causar alguma estranheza, mas não! Ainda nos dias de
hoje se aceita com normalidade que o ensino se dê somente com os
recursos básicos quadro e giz, embora tenhamos tecnologia suficiente
para fazer melhor. 

A concorrência que os iPhones conectados a internet fazem ao professor
e seu quadro/giz chega a ser desleal; os jovens estão desmotivados com
a escola e seus métodos tradicionais mas sedentos pelas novas
tecnologias. No intuito de aproximar a escola dos meios tecnológicos,
profissionais da educação tem se preocupado em traçar estratégias para
fazer bom proveito da tecnologia nas escolas, visto que apenas inserir
o computador na sala de aula, sem um prévio planejamento de uso dos
seus recursos, resultará certamente em fracasso. 

Para haver uma evolução  positiva do processo ensino-aprendizagem,
deve haver um uso adequado e inovador das tecnologias no ambiente
escolar. Visando essas formas inovadoras de inserção da tecnologia na
sala de aula, muitos materiais digitais são lançados a fim de tornar a
aprendizagem mais efetiva. A esses materiais damos o nome de *Objetos
Digitais de Aprendizagem*, e serão eles o foco do nosso curso.



=== Público alvo

O público alvo desse livro são os alunos de Licenciatura em
Computação, na modalidade à distância footnote::[Embora ele tenha sido
feito para atender aos alunos da Universidade Federal da Paraíba, o
seu uso não se restringe a esta  universidade, podendo ser adotado por
outras universidades do sistema UAB.]. Ele foi concebido para ser
utilizado numa disciplina de 'Introdução à Computação', no primeiro
semestre do curso.

[[como_estudar]]
=== Como você deve estudar cada capítulo

* Leia a visão geral do capítulo
* Estude os conteúdos das seções
* Realize as atividades no final do capítulo
* Verifique se você atingiu os objetivos do capítulo

.Na sala de aula do curso
* Tire dúvidas e discuta sobre as atividades do livro com outros integrantes do curso
* Leia materiais complementares eventualmente disponibilizados
* Realize as atividades propostas pelo professor da disciplina


////
Sempre terminar o arquivo com uma nova linha.
////

